name: NDK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          wget -O './ndk/src/util_functions.hpp' 'https://raw.githubusercontent.com/iamlooper/Utils/cpp-utils/util_functions.hpp
          
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c

      - name: Compile
        run: |
          ndk-build NDK_PROJECT_PATH='./ndk' APP_BUILD_SCRIPT='./ndk/Android.mk' NDK_APPLICATION_MK='./ndk/Application.mk'
          
      - name: Make build folder
        run: |
          mkdir -p './NRAO'
          cp -af './ndk/libs' './NRAO'
          cp -f './run.sh' './NRAO'
          cp -f './module.prop' './NRAO'
                 
      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: NRAO
          path: './NRAO'

